services:
  postgres:
    build:
      dockerfile: images/postgres.dockerfile
    environment:
      POSTGRES_USER: ash
      POSTGRES_DB: pokedex
      POSTGRES_PASSWORD: pikachu
    networks:
      - kanto
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ash@pokedex.com
      PGADMIN_DEFAULT_PASSWORD: pikachu
    volumes:
      - ${PWD}/pgadmin_servers.json:/pgadmin4/servers.json
    networks:
      - kanto
    ports:
      - 50151:80

  # tcgdex:
  #   build:
  #     dockerfile: images/tcgdex.dockerfile
  #   environment:
  #     POSTGRES_URL: postgresql://ash:pikachu@postgres:5432/pokedex
  #   volumes:
  #     - ${PWD}/data:/app/data
  #     - ${PWD}/tmp:/app/tmp
  #     - ${PWD}/data_config.json:/app/data_config.json
  #   networks:
  #     - kanto
  #   ports:
  #     - 8000:8000 # sidecar
  #     - 8001:8001 # go
  #     - 8501:8501 # front
  #   tty: true


networks:
  kanto:
    driver: bridge 

